Ruben/ean validation
api-testing-01/coding pull request #34
Opened 2019-11-12 22:08 UTC by mendozard

Hi Carlos, I just realized I haven't asked merge before. The last commit was done on Oct 30

2019-11-19 22:59 UTC, carledriss requested changes

2019-11-19 22:59 UTC, carledriss commented on src/main/java/org/fundacionjala/coding/ruben/EANValidator.java
> +    public static boolean validate(final String eanCode) {
This kata can be solved with a single for.
Could you try to refactor it ?

2019-11-20 16:34 UTC, RubenMendozaP commented
@carledriss  Changes made. Also cleaned up format according to Best Practices

2019-11-20 18:44 UTC, carledriss approved these changes

2019-11-20 18:44 UTC, merged